import turtle
alex = turtle.Turtle()
alex.goto(10,10)
alex.seth(90)
floor = turtle.Screen()
alex.forward(150)
alex.left(90)
alex.forward(150)
alex.left(135)
alex.forward(212)
print(alex.pos())
floor.exitonclick()
